apiVersion:  apps/v1 # Версия API
kind: Pod # Объект, который создаем
metadata:
  name: nginx-web-otus # Название Pod
  labels: # Метки в формате key: value
    web: nginx
spec: # Описание Pod
  containers: # Описание контейнеров внутри Pod
  - name: nginx # Название контейнера
    image: andreyeus/otus-nginx:1
    volumeMounts:
    - name: app
      mountPath: /app
  initContainers:
  - name: busybox
    image: busybox:latest
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
    - name: app
      mountPath: /app
  volumes:
  - name: app
    emptyDir: {}
